import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "./ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vinaya Studies",
  description: "Generated by dukkha",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="./favicon.ico?v=2" />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
